spring:
  datasource:
    password: todak@123
    username: todak
    url: jdbc:postgresql://127.0.0.1:5432/authentication
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  flyway:
    enabled: true
  redis:
    port: 6379
    host: 127.0.0.1

jwt:
  secret: JAIUwkdjf238fJDASLdkbhzVDseordi
  token-validity-in-milliseconds: 100000