CREATE TABLE ACCOUNT (
  ACCOUNT_ID BIGINT PRIMARY KEY,
  USERNAME VARCHAR(60) NOT NULL UNIQUE,
  PASSWORD VARCHAR(200) NOT NULL UNIQUE,
  ENROLLED_DATE_TIME TIMESTAMP NOT NULL,
  UPDATED_DATE_TIME TIMESTAMP NOT NULL
);